spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wordcloud
    username: wordcloud
    password: wordcloud
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: wordcloud
    password: wordcloud

wordcloud:
  rabbitmq:
    queue: wordcloud.text.queue
