spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wordcloud
    username: wordcloud
    password: wordcloud
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: wordcloud
    password: wordcloud
    listener:
      simple:
        missing-queues-fatal: false

wordcloud:
  rabbitmq:
    queue: wordcloud.text.queue
